# CMake generated Testfile for 
# Source directory: /SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots
# Build directory: /SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(python.plots.datafunctionsTest.datafunctionsTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/datafunctionsTest.py")
set_tests_properties(python.plots.datafunctionsTest.datafunctionsTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots::;QT_API=pyqt5" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;15;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;0;")
add_test(python.plots.axesfunctionsTest.axesfunctionsTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/axesfunctionsTest.py")
set_tests_properties(python.plots.axesfunctionsTest.axesfunctionsTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots::;QT_API=pyqt5" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;15;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;0;")
add_test(python.plots.axesfunctions3DTest.axesfunctions3DTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/axesfunctions3DTest.py")
set_tests_properties(python.plots.axesfunctions3DTest.axesfunctions3DTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots::;QT_API=pyqt5" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;15;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;0;")
add_test(python.plots.plotfunctionsTest.plotfunctionsTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/plotfunctionsTest.py")
set_tests_properties(python.plots.plotfunctionsTest.plotfunctionsTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots::;QT_API=pyqt5" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;15;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;0;")
add_test(python.plots.mantidaxesTest.mantidaxesTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/mantidaxesTest.py")
set_tests_properties(python.plots.mantidaxesTest.mantidaxesTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots::;QT_API=pyqt5" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;15;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;0;")
add_test(python.plots.ScalesTest.ScalesTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/ScalesTest.py")
set_tests_properties(python.plots.ScalesTest.ScalesTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots::;QT_API=pyqt5" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;15;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;0;")
add_test(python.plots.UtilityTest.UtilityTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/UtilityTest.py")
set_tests_properties(python.plots.UtilityTest.UtilityTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots::;QT_API=pyqt5" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;15;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;0;")
add_test(python.plots.compatabilityTest.compatabilityTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/compatabilityTest.py")
set_tests_properties(python.plots.compatabilityTest.compatabilityTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots::;QT_API=pyqt5" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;15;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;0;")
add_test(python.plots.surfacecontourplotsTest.surfacecontourplotsTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/surfacecontourplotsTest.py")
set_tests_properties(python.plots.surfacecontourplotsTest.surfacecontourplotsTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots::;QT_API=pyqt5" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;15;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;0;")
add_test(python.plots.legendTest.legendTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/legendTest.py")
set_tests_properties(python.plots.legendTest.legendTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots::;QT_API=pyqt5" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;15;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/CMakeLists.txt;0;")
subdirs("modest_image")
