# CMake generated Testfile for 
# Source directory: /SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid
# Build directory: /SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(python.ImportModuleTest.ImportModuleTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/ImportModuleTest.py")
set_tests_properties(python.ImportModuleTest.ImportModuleTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/CMakeLists.txt;19;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/CMakeLists.txt;0;")
add_test(python.SimpleAPITest.SimpleAPITest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/SimpleAPITest.py")
set_tests_properties(python.SimpleAPITest.SimpleAPITest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/CMakeLists.txt;19;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/CMakeLists.txt;0;")
add_test(python.SimpleAPILoadTest.SimpleAPILoadTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/SimpleAPILoadTest.py")
set_tests_properties(python.SimpleAPILoadTest.SimpleAPILoadTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/CMakeLists.txt;19;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/CMakeLists.txt;0;")
add_test(python.SimpleAPIFitTest.SimpleAPIFitTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/SimpleAPIFitTest.py")
set_tests_properties(python.SimpleAPIFitTest.SimpleAPIFitTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/CMakeLists.txt;19;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/CMakeLists.txt;0;")
add_test(python.SimpleAPIRenameWorkspaceTest.SimpleAPIRenameWorkspaceTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/SimpleAPIRenameWorkspaceTest.py")
set_tests_properties(python.SimpleAPIRenameWorkspaceTest.SimpleAPIRenameWorkspaceTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/CMakeLists.txt;19;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/CMakeLists.txt;0;")
add_test(python.FitFunctionsTest.FitFunctionsTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/FitFunctionsTest.py")
set_tests_properties(python.FitFunctionsTest.FitFunctionsTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/CMakeLists.txt;19;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/CMakeLists.txt;0;")
subdirs("kernel")
subdirs("geometry")
subdirs("api")
subdirs("dataobjects")
subdirs("plots")
subdirs("utils")
subdirs("_plugins")
