
#ifndef MANTID_REFLECTOMETRY_DLL_H
#define MANTID_REFLECTOMETRY_DLL_H

#ifdef MANTID_REFLECTOMETRY_STATIC_DEFINE
#  define MANTID_REFLECTOMETRY_DLL
#  define MANTID_REFLECTOMETRY_NO_EXPORT
#else
#  ifndef MANTID_REFLECTOMETRY_DLL
#    ifdef Reflectometry_EXPORTS
        /* We are building this library */
#      define MANTID_REFLECTOMETRY_DLL __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define MANTID_REFLECTOMETRY_DLL __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef MANTID_REFLECTOMETRY_NO_EXPORT
#    define MANTID_REFLECTOMETRY_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef MANTID_REFLECTOMETRY_DEPRECATED
#  define MANTID_REFLECTOMETRY_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef MANTID_REFLECTOMETRY_DEPRECATED_EXPORT
#  define MANTID_REFLECTOMETRY_DEPRECATED_EXPORT MANTID_REFLECTOMETRY_DLL MANTID_REFLECTOMETRY_DEPRECATED
#endif

#ifndef MANTID_REFLECTOMETRY_DEPRECATED_NO_EXPORT
#  define MANTID_REFLECTOMETRY_DEPRECATED_NO_EXPORT MANTID_REFLECTOMETRY_NO_EXPORT MANTID_REFLECTOMETRY_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef MANTID_REFLECTOMETRY_NO_DEPRECATED
#    define MANTID_REFLECTOMETRY_NO_DEPRECATED
#  endif
#endif

#ifndef UNUSED_ARG
    #define UNUSED_ARG(x) (void) x;
#endif

#ifndef REFLECTOMETRY_DEPRECATED
    #define REFLECTOMETRY_DEPRECATED(func) MANTID_REFLECTOMETRY_DEPRECATED func
#endif


#endif
