# CMake generated Testfile for 
# Source directory: /SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/dataobjects
# Build directory: /SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/dataobjects
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(python.dataobjects.EventListTest.EventListTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/dataobjects/EventListTest.py")
set_tests_properties(python.dataobjects.EventListTest.EventListTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/dataobjects::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/dataobjects/CMakeLists.txt;10;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/dataobjects/CMakeLists.txt;0;")
add_test(python.dataobjects.Workspace2DPickleTest.Workspace2DPickleTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/dataobjects/Workspace2DPickleTest.py")
set_tests_properties(python.dataobjects.Workspace2DPickleTest.Workspace2DPickleTest PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/dataobjects::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/dataobjects/CMakeLists.txt;10;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/dataobjects/CMakeLists.txt;0;")
