# CMake generated Testfile for 
# Source directory: /SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp
# Build directory: /SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(PythonInterfaceCppTest_IFunction1DAdapterTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/PythonInterfaceCppTest" "IFunction1DAdapterTest")
set_tests_properties(PythonInterfaceCppTest_IFunction1DAdapterTest PROPERTIES  ENVIRONMENT "PYTHONPATH=:/SNS/users/zgf/.git/mantid/Framework/PythonInterface::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;20;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;0;")
add_test(PythonInterfaceCppTest_IPeakFunctionAdapterTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/PythonInterfaceCppTest" "IPeakFunctionAdapterTest")
set_tests_properties(PythonInterfaceCppTest_IPeakFunctionAdapterTest PROPERTIES  ENVIRONMENT "PYTHONPATH=:/SNS/users/zgf/.git/mantid/Framework/PythonInterface::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;20;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;0;")
add_test(PythonInterfaceCppTest_PropertyWithValueFactoryTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/PythonInterfaceCppTest" "PropertyWithValueFactoryTest")
set_tests_properties(PythonInterfaceCppTest_PropertyWithValueFactoryTest PROPERTIES  ENVIRONMENT "PYTHONPATH=:/SNS/users/zgf/.git/mantid/Framework/PythonInterface::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;20;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;0;")
add_test(PythonInterfaceCppTest_PythonAlgorithmInstantiatorTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/PythonInterfaceCppTest" "PythonAlgorithmInstantiatorTest")
set_tests_properties(PythonInterfaceCppTest_PythonAlgorithmInstantiatorTest PROPERTIES  ENVIRONMENT "PYTHONPATH=:/SNS/users/zgf/.git/mantid/Framework/PythonInterface::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;20;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;0;")
add_test(PythonInterfaceCppTest_PySequenceToVectorTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/PythonInterfaceCppTest" "PySequenceToVectorTest")
set_tests_properties(PythonInterfaceCppTest_PySequenceToVectorTest PROPERTIES  ENVIRONMENT "PYTHONPATH=:/SNS/users/zgf/.git/mantid/Framework/PythonInterface::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;20;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;0;")
add_test(PythonInterfaceCppTest_RunPythonScriptTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/PythonInterfaceCppTest" "RunPythonScriptTest")
set_tests_properties(PythonInterfaceCppTest_RunPythonScriptTest PROPERTIES  ENVIRONMENT "PYTHONPATH=:/SNS/users/zgf/.git/mantid/Framework/PythonInterface::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;20;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;0;")
add_test(PythonInterfaceCppTest_ToPyListTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/PythonInterfaceCppTest" "ToPyListTest")
set_tests_properties(PythonInterfaceCppTest_ToPyListTest PROPERTIES  ENVIRONMENT "PYTHONPATH=:/SNS/users/zgf/.git/mantid/Framework/PythonInterface::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;20;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/cpp/CMakeLists.txt;0;")
