# CMake generated Testfile for 
# Source directory: /SNS/users/zgf/.git/mantid/Framework/LiveData/test
# Build directory: /SNS/users/zgf/.git/mantid/Framework/LiveData/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(LiveDataTest_ADARAPacketTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/LiveDataTest" "ADARAPacketTest")
set_tests_properties(LiveDataTest_ADARAPacketTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;21;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;0;")
add_test(LiveDataTest_FakeEventDataListenerTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/LiveDataTest" "FakeEventDataListenerTest")
set_tests_properties(LiveDataTest_FakeEventDataListenerTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;21;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;0;")
add_test(LiveDataTest_FileEventDataListenerTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/LiveDataTest" "FileEventDataListenerTest")
set_tests_properties(LiveDataTest_FileEventDataListenerTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;21;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;0;")
add_test(LiveDataTest_ISISHistoDataListenerTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/LiveDataTest" "ISISHistoDataListenerTest")
set_tests_properties(LiveDataTest_ISISHistoDataListenerTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;21;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;0;")
add_test(LiveDataTest_LiveDataAlgorithmTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/LiveDataTest" "LiveDataAlgorithmTest")
set_tests_properties(LiveDataTest_LiveDataAlgorithmTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;21;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;0;")
add_test(LiveDataTest_LoadLiveDataTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/LiveDataTest" "LoadLiveDataTest")
set_tests_properties(LiveDataTest_LoadLiveDataTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;21;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;0;")
add_test(LiveDataTest_MonitorLiveDataTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/LiveDataTest" "MonitorLiveDataTest")
set_tests_properties(LiveDataTest_MonitorLiveDataTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;21;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;0;")
add_test(LiveDataTest_StartLiveDataTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/LiveDataTest" "StartLiveDataTest")
set_tests_properties(LiveDataTest_StartLiveDataTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;21;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;0;")
add_test(LiveDataTest_KafkaEventStreamDecoderTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/LiveDataTest" "KafkaEventStreamDecoderTest")
set_tests_properties(LiveDataTest_KafkaEventStreamDecoderTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;21;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;0;")
add_test(LiveDataTest_KafkaHistoStreamDecoderTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/LiveDataTest" "KafkaHistoStreamDecoderTest")
set_tests_properties(LiveDataTest_KafkaHistoStreamDecoderTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;21;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;0;")
add_test(LiveDataTest_KafkaTopicSubscriberTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/LiveDataTest" "KafkaTopicSubscriberTest")
set_tests_properties(LiveDataTest_KafkaTopicSubscriberTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;21;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/LiveData/test/CMakeLists.txt;0;")
