# CMake generated Testfile for 
# Source directory: /SNS/users/zgf/.git/mantid/Framework/Parallel/test
# Build directory: /SNS/users/zgf/.git/mantid/Framework/Parallel/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ParallelTest_ChunkerTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ParallelTest" "ChunkerTest")
set_tests_properties(ParallelTest_ChunkerTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;11;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;0;")
add_test(ParallelTest_CollectivesTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ParallelTest" "CollectivesTest")
set_tests_properties(ParallelTest_CollectivesTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;11;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;0;")
add_test(ParallelTest_CommunicatorTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ParallelTest" "CommunicatorTest")
set_tests_properties(ParallelTest_CommunicatorTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;11;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;0;")
add_test(ParallelTest_EventDataPartitionerTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ParallelTest" "EventDataPartitionerTest")
set_tests_properties(ParallelTest_EventDataPartitionerTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;11;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;0;")
add_test(ParallelTest_EventLoaderTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ParallelTest" "EventLoaderTest")
set_tests_properties(ParallelTest_EventLoaderTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;11;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;0;")
add_test(ParallelTest_EventParserTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ParallelTest" "EventParserTest")
set_tests_properties(ParallelTest_EventParserTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;11;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;0;")
add_test(ParallelTest_ExecutionModeTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ParallelTest" "ExecutionModeTest")
set_tests_properties(ParallelTest_ExecutionModeTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;11;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;0;")
add_test(ParallelTest_NonblockingTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ParallelTest" "NonblockingTest")
set_tests_properties(ParallelTest_NonblockingTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;11;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;0;")
add_test(ParallelTest_ParallelRunnerTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ParallelTest" "ParallelRunnerTest")
set_tests_properties(ParallelTest_ParallelRunnerTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;11;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;0;")
add_test(ParallelTest_PulseTimeGeneratorTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ParallelTest" "PulseTimeGeneratorTest")
set_tests_properties(ParallelTest_PulseTimeGeneratorTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;11;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;0;")
add_test(ParallelTest_RequestTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ParallelTest" "RequestTest")
set_tests_properties(ParallelTest_RequestTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;11;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;0;")
add_test(ParallelTest_StorageModeTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ParallelTest" "StorageModeTest")
set_tests_properties(ParallelTest_StorageModeTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;11;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;0;")
add_test(ParallelTest_ThreadingBackendTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ParallelTest" "ThreadingBackendTest")
set_tests_properties(ParallelTest_ThreadingBackendTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;11;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/Parallel/test/CMakeLists.txt;0;")
