# CMake generated Testfile for 
# Source directory: /SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test
# Build directory: /SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(WorkflowAlgorithmsTest_AlignAndFocusPowderTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/WorkflowAlgorithmsTest" "AlignAndFocusPowderTest")
set_tests_properties(WorkflowAlgorithmsTest_AlignAndFocusPowderTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;15;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;0;")
add_test(WorkflowAlgorithmsTest_ExtractQENSMembersTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/WorkflowAlgorithmsTest" "ExtractQENSMembersTest")
set_tests_properties(WorkflowAlgorithmsTest_ExtractQENSMembersTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;15;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;0;")
add_test(WorkflowAlgorithmsTest_IMuonAsymmetryCalculatorTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/WorkflowAlgorithmsTest" "IMuonAsymmetryCalculatorTest")
set_tests_properties(WorkflowAlgorithmsTest_IMuonAsymmetryCalculatorTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;15;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;0;")
add_test(WorkflowAlgorithmsTest_LoadEventAndCompressTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/WorkflowAlgorithmsTest" "LoadEventAndCompressTest")
set_tests_properties(WorkflowAlgorithmsTest_LoadEventAndCompressTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;15;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;0;")
add_test(WorkflowAlgorithmsTest_MuonProcessTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/WorkflowAlgorithmsTest" "MuonProcessTest")
set_tests_properties(WorkflowAlgorithmsTest_MuonProcessTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;15;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;0;")
add_test(WorkflowAlgorithmsTest_ProcessIndirectFitParametersTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/WorkflowAlgorithmsTest" "ProcessIndirectFitParametersTest")
set_tests_properties(WorkflowAlgorithmsTest_ProcessIndirectFitParametersTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;15;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;0;")
add_test(WorkflowAlgorithmsTest_SANSSolidAngleCorrectionTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/WorkflowAlgorithmsTest" "SANSSolidAngleCorrectionTest")
set_tests_properties(WorkflowAlgorithmsTest_SANSSolidAngleCorrectionTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;15;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;0;")
add_test(WorkflowAlgorithmsTest_SofTwoThetaTOFTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/WorkflowAlgorithmsTest" "SofTwoThetaTOFTest")
set_tests_properties(WorkflowAlgorithmsTest_SofTwoThetaTOFTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;15;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;0;")
add_test(WorkflowAlgorithmsTest_StepScanTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/WorkflowAlgorithmsTest" "StepScanTest")
set_tests_properties(WorkflowAlgorithmsTest_StepScanTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;15;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/WorkflowAlgorithms/test/CMakeLists.txt;0;")
