# CMake generated Testfile for 
# Source directory: /SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test
# Build directory: /SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(NexusGeometryTest_InstrumentBuilderTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/NexusGeometryTest" "InstrumentBuilderTest")
set_tests_properties(NexusGeometryTest_InstrumentBuilderTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;12;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;0;")
add_test(NexusGeometryTest_JSONInstrumentBuilderTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/NexusGeometryTest" "JSONInstrumentBuilderTest")
set_tests_properties(NexusGeometryTest_JSONInstrumentBuilderTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;12;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;0;")
add_test(NexusGeometryTest_NexusGeometryParserTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/NexusGeometryTest" "NexusGeometryParserTest")
set_tests_properties(NexusGeometryTest_NexusGeometryParserTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;12;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;0;")
add_test(NexusGeometryTest_NexusGeometrySaveTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/NexusGeometryTest" "NexusGeometrySaveTest")
set_tests_properties(NexusGeometryTest_NexusGeometrySaveTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;12;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;0;")
add_test(NexusGeometryTest_JSONGeometryParserTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/NexusGeometryTest" "JSONGeometryParserTest")
set_tests_properties(NexusGeometryTest_JSONGeometryParserTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;12;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;0;")
add_test(NexusGeometryTest_NexusShapeFactoryTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/NexusGeometryTest" "NexusShapeFactoryTest")
set_tests_properties(NexusGeometryTest_NexusShapeFactoryTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;12;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;0;")
add_test(NexusGeometryTest_TubeBuilderTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/NexusGeometryTest" "TubeBuilderTest")
set_tests_properties(NexusGeometryTest_TubeBuilderTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;12;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;0;")
add_test(NexusGeometryTest_TubeHelpersTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/NexusGeometryTest" "TubeHelpersTest")
set_tests_properties(NexusGeometryTest_TubeHelpersTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;12;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/NexusGeometry/test/CMakeLists.txt;0;")
