# CMake generated Testfile for 
# Source directory: /SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/modest_image
# Build directory: /SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/modest_image
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(python.plots.modest_image.test_imshow.test_imshow "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/modest_image/test_imshow.py")
set_tests_properties(python.plots.modest_image.test_imshow.test_imshow PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/modest_image::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/modest_image/CMakeLists.txt;10;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/modest_image/CMakeLists.txt;0;")
add_test(python.plots.modest_image.test_modest_image.test_modest_image "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/mantidpython" "--classic" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/modest_image/test_modest_image.py")
set_tests_properties(python.plots.modest_image.test_modest_image.test_modest_image PROPERTIES  ENVIRONMENT "PYTHONPATH=/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/modest_image::" TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/PyUnitTest.cmake;53;add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/modest_image/CMakeLists.txt;10;pyunittest_add_test;/SNS/users/zgf/.git/mantid/Framework/PythonInterface/test/python/mantid/plots/modest_image/CMakeLists.txt;0;")
