# CMake generated Testfile for 
# Source directory: /SNS/users/zgf/.git/mantid/Framework/ICat/test
# Build directory: /SNS/users/zgf/.git/mantid/Framework/ICat/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ICatTest_CatalogDownloadDataFilesTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ICatTest" "CatalogDownloadDataFilesTest")
set_tests_properties(ICatTest_CatalogDownloadDataFilesTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;14;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;0;")
add_test(ICatTest_CatalogGetDataFilesTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ICatTest" "CatalogGetDataFilesTest")
set_tests_properties(ICatTest_CatalogGetDataFilesTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;14;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;0;")
add_test(ICatTest_CatalogGetDataSetsTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ICatTest" "CatalogGetDataSetsTest")
set_tests_properties(ICatTest_CatalogGetDataSetsTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;14;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;0;")
add_test(ICatTest_CatalogListInstrumentsTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ICatTest" "CatalogListInstrumentsTest")
set_tests_properties(ICatTest_CatalogListInstrumentsTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;14;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;0;")
add_test(ICatTest_CatalogListInvestigationTypesTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ICatTest" "CatalogListInvestigationTypesTest")
set_tests_properties(ICatTest_CatalogListInvestigationTypesTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;14;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;0;")
add_test(ICatTest_CatalogLoginTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ICatTest" "CatalogLoginTest")
set_tests_properties(ICatTest_CatalogLoginTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;14;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;0;")
add_test(ICatTest_CatalogMyDataSearchTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ICatTest" "CatalogMyDataSearchTest")
set_tests_properties(ICatTest_CatalogMyDataSearchTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;14;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;0;")
add_test(ICatTest_CatalogSearchTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ICatTest" "CatalogSearchTest")
set_tests_properties(ICatTest_CatalogSearchTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;14;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;0;")
add_test(ICatTest_CompositeCatalogTest "/usr/bin/cmake3" "-E" "chdir" "/SNS/users/zgf/.git/mantid/bin/Testing" "/SNS/users/zgf/.git/mantid/bin/ICatTest" "CompositeCatalogTest")
set_tests_properties(ICatTest_CompositeCatalogTest PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/SNS/users/zgf/.git/mantid/buildconfig/CMake/FindCxxTest.cmake;188;add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;14;cxxtest_add_test;/SNS/users/zgf/.git/mantid/Framework/ICat/test/CMakeLists.txt;0;")
